apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delay
  template:
    hostNetwork: true
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: registry:2
        name: server
